#!/bin/bash
set -e

ENDPOINT="http://localhost:4566"
REGION="us-east-1"

export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_DEFAULT_REGION=$REGION

echo "🧪 Testing Local PoC: Callback Pattern (TypeScript)"
echo "===================================================="
echo ""

# Start execution
echo "1️⃣  Starting Step Functions execution..."

EXECUTION_ARN=$(aws --endpoint-url=$ENDPOINT stepfunctions start-execution \
  --state-machine-arn arn:aws:states:$REGION:000000000000:stateMachine:poc-callback-workflow \
  --name "test-$(date +%s)" \
  --query 'executionArn' \
  --output text)

echo "   ✅ Execution started: $EXECUTION_ARN"
echo ""

# Wait for job to be created
echo "   ⏳ Waiting for job creation (3 seconds)..."
sleep 3

# Get job ID from DynamoDB
echo ""
echo "2️⃣  Checking job created in DynamoDB..."
JOB_ID=$(aws --endpoint-url=$ENDPOINT dynamodb scan \
  --table-name poc-task-tokens \
  --filter-expression "#s = :polling" \
  --expression-attribute-names '{"#s": "status"}' \
  --expression-attribute-values '{":polling": {"S": "POLLING"}}' \
  --query 'Items[0].jobId.S' \
  --output text)

if [ "$JOB_ID" == "None" ] || [ -z "$JOB_ID" ]; then
  echo "   ❌ No job found. Check Lambda logs:"
  echo "      docker logs localstack-poc 2>&1 | grep -A 20 'CreateJob'"
  exit 1
fi

echo "   ✅ Job created: $JOB_ID"
echo ""

# Check execution status
STATUS=$(aws --endpoint-url=$ENDPOINT stepfunctions describe-execution \
  --execution-arn "$EXECUTION_ARN" \
  --query 'status' \
  --output text)

echo "3️⃣  Step Functions status: $STATUS"
if [ "$STATUS" == "RUNNING" ]; then
  echo "   ✅ Workflow is WAITING for callback (Task Token pattern working!)"
else
  echo "   ⚠️  Expected RUNNING status, got: $STATUS"
fi
echo ""

# Manual polling loop
echo "4️⃣  Starting manual polling (simulating EventBridge Scheduler)..."
echo "   Polling every 5 seconds until job completes..."
echo ""

POLL_COUNT=0
MAX_POLLS=10

while [ $POLL_COUNT -lt $MAX_POLLS ]; do
  POLL_COUNT=$((POLL_COUNT + 1))

  echo "   📊 Poll #$POLL_COUNT..."

  # Invoke poller Lambda
  POLL_RESULT=$(aws --endpoint-url=$ENDPOINT lambda invoke \
    --function-name poc-poller \
    --payload "{\"jobId\": \"$JOB_ID\"}" \
    --cli-binary-format raw-in-base64-out \
    /dev/stdout 2>/dev/null | head -1)

  echo "      Result: $POLL_RESULT"

  # Check if completed
  if echo "$POLL_RESULT" | grep -q '"status":"COMPLETED"'; then
    echo ""
    echo "   🎉 Job completed and workflow reconnected!"
    break
  fi

  if echo "$POLL_RESULT" | grep -q '"reconnected":true'; then
    echo ""
    echo "   🎉 Workflow reconnected via SendTaskSuccess!"
    break
  fi

  sleep 5
done

echo ""
echo "   ⏳ Waiting for workflow to complete (2 seconds)..."
sleep 2

# Check final execution status
echo ""
echo "5️⃣  Checking final execution status..."

FINAL_STATUS=$(aws --endpoint-url=$ENDPOINT stepfunctions describe-execution \
  --execution-arn "$EXECUTION_ARN" \
  --query 'status' \
  --output text)

echo "   Final Status: $FINAL_STATUS"

if [ "$FINAL_STATUS" == "SUCCEEDED" ]; then
  echo ""
  echo "✅ TEST PASSED! Workflow completed successfully!"
  echo ""
  echo "📋 Execution Output:"
  aws --endpoint-url=$ENDPOINT stepfunctions describe-execution \
    --execution-arn "$EXECUTION_ARN" \
    --query 'output' \
    --output text | jq . 2>/dev/null || cat
else
  echo ""
  echo "❌ TEST FAILED. Status: $FINAL_STATUS"
  echo ""
  echo "Execution details:"
  aws --endpoint-url=$ENDPOINT stepfunctions describe-execution \
    --execution-arn "$EXECUTION_ARN"
fi

echo ""
echo "6️⃣  Pattern Validation Summary:"
echo "   ✅ Task Token generated by Step Functions"
echo "   ✅ Token persisted in DynamoDB"
echo "   ✅ External polling (simulated EventBridge Scheduler)"
echo "   ✅ SendTaskSuccess reconnected workflow"
echo "   ✅ Workflow completed after callback"
echo ""
echo "🎯 TypeScript implementation validated successfully!"
